# Generated by Django 5.2 on 2025-06-03 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instsoli', '0012_semestreavaliativo_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('aula', models.PositiveIntegerField(default=0)),
                ('documento', models.FileField(blank=True, null=True, upload_to='materiais/')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('Vídeo', 'Vídeo'), ('Link', 'Link')], max_length=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instsoli.curso')),
            ],
        ),
    ]
